fix add and submit

diff --git a/mygive-submit b/mygive-submit
--- a/mygive-submit
+++ b/mygive-submit
@@ -6,8 +6,9 @@ file_name=$3
 
 test_regex="^[a-zA-Z0-9._/\-]+$"
 
-if [ ! -d ".mygive/$ass_name/$zid" ];then
-    mkdir ".mygive/$ass_name/$zid"
+if ! test -d ".take/$ass_name"; then
+    echo "mygive-submit: assignment $ass_name not found" 1>&2
+    exit 1
 fi
 
 if ! echo "$zid" | grep -qE '^z[0-9]{7}$';then
@@ -23,6 +24,15 @@ fi
 if ! test -f "$file_name";then
     echo "mygive-submit: $file_name: No such file or directory" 1>&2
     exit 1
+fi
+
+if test $# != 3; then
+    echo "usage: mygive-submit <assignment> <zid> <filename>" >&2
+    exit 1
+fi 
+
+if [ ! -d ".mygive/$ass_name/$zid" ];then
+    mkdir ".mygive/$ass_name/$zid"
 fi
 
 max_index=$( ls -1d ".mygive/$ass_name/$zid/"* 2>/dev/null | sed 's/.*\///' | sort | tail -n1)
