finish tests

diff --git a/mygive-test b/mygive-test
--- a/mygive-test
+++ b/mygive-test
@@ -3,7 +3,7 @@
 if [ $# -ne 2 ]; then
     echo "usage: mygive-test <assignment> <filename>" 1>&2
     exit 1
-fi  
+fi
 
 ass_name="$1"
 program_file="$2"
@@ -30,15 +30,15 @@ passed_tests=0
 failed_tests=0
 
 for test_file in .mygive/$ass_name/tests/*; do
-   test_dir=$(basename $test_file | cut -d'.' -f1)
-   mkdir -p "$test_dir"
-   tar --warning=no-timestamp -xf "$test_file" -C "$test_dir"
+    test_dir=$(basename $test_file | cut -d'.' -f1)
+    mkdir -p "$test_dir"
+    tar --warning=no-timestamp -xf "$test_file" -C "$test_dir"
 
-   tmp_list=$(mktemp)
-   find "$test_dir" -mindepth 1 -type d | sort > "$tmp_list"
+    tmp_list=$(mktemp)
+    find "$test_dir" -mindepth 1 -type d | sort >"$tmp_list"
 
-   while read -r file_dir; do
-        if find "$file_dir" -type f -name "*marks*" | grep -q .;then
+    while read -r file_dir; do
+        if find "$file_dir" -type f -name "*marks*" | grep -q .; then
             # echo "$file_dir"
             continue
         fi
@@ -55,23 +55,23 @@ for test_file in .mygive/$ass_name/tests/*; do
         expected_stdout_file=$(mktemp)
         expected_stderr_file=$(mktemp)
 
-         if [ -f "./$file_dir/exit_status" ];then
+        if [ -f "./$file_dir/exit_status" ]; then
             exit_status=$(cat "./$file_dir/exit_status")
         fi
-        
-        if [ -f "./$file_dir/arguments" ];then
+
+        if [ -f "./$file_dir/arguments" ]; then
             arguments=$(cat "./$file_dir/arguments")
-            if ! echo "$arguments" | grep -Eq "$arguments_regex";then
+            if ! echo "$arguments" | grep -Eq "$arguments_regex"; then
                 echo "mygive-test: invalid arguments: $arguments" 1>&2
                 exit "$exit_status"
             fi
         fi
 
-        if [ -f "./$file_dir/stdin" ];then
+        if [ -f "./$file_dir/stdin" ]; then
             stdin=$(cat "./$file_dir/stdin")
         fi
 
-        if [ -f "./$file_dir/options" ];then
+        if [ -f "./$file_dir/options" ]; then
             options=$(cat "./$file_dir/options")
         fi
 
@@ -80,35 +80,42 @@ for test_file in .mygive/$ass_name/tests/*; do
         # echo "stdout: $stdout"
         # echo "stderr: $stderr"
 
-        if [ -z "$stdin" ];then
-            ./"$program_file" $arguments > "$result_stdout_file" 2> "$result_stderr_file"
+        if [ -z "$stdin" ]; then
+            ./"$program_file" $arguments >"$result_stdout_file" 2>"$result_stderr_file"
         else
-            echo "$stdin" | ./"$program_file" $arguments > "$result_stdout_file" 2> "$result_stderr_file"
+            echo "$stdin" | ./"$program_file" $arguments >"$result_stdout_file" 2>"$result_stderr_file"
         fi
+        result_exit_code="$?"
 
-        if [ -f "./$file_dir/stdout" ];then
+        if [ -f "./$file_dir/stdout" ]; then
             cp "./$file_dir/stdout" "$expected_stdout_file"
         else
-            : > "$expected_stdout_file"
+            : >"$expected_stdout_file"
+        fi
+
+        if [ -f "./$file_dir/stderr" ]; then
+            cp "./$file_dir/stderr" "$expected_stderr_file"
+        else
+            : >"$expected_stderr_file"
         fi
         tmp_file=$(mktemp)
 
-            if echo "$options" | grep -q "b"; then
-                sed -i "/^$/d" "$result_stdout_file"
-                sed -i "/^$/d" "$expected_stdout_file"
-            fi
+        if echo "$options" | grep -q "b"; then
+            sed -i "/^$/d" "$result_stdout_file"
+            sed -i "/^$/d" "$expected_stdout_file"
+        fi
 
-            if echo "$options" | grep -q "c"; then
-                tr '[:upper:]' '[:lower:]' < "$result_stdout_file" > "$tmp_file"
-                mv "$tmp_file" "$result_stdout_file"
-                tr '[:upper:]' '[:lower:]' < "$expected_stdout_file" > "$tmp_file"
-                mv "$tmp_file" "$expected_stdout_file"
-            fi
-
-       if echo "$options" | grep -q "w"; then
-           tr -d ' \t' < "$result_stdout_file" > "$tmp_file"
+        if echo "$options" | grep -q "c"; then
+            tr '[:upper:]' '[:lower:]' <"$result_stdout_file" >"$tmp_file"
             mv "$tmp_file" "$result_stdout_file"
-            tr -d ' \t' < "$expected_stdout_file" > "$tmp_file"
+            tr '[:upper:]' '[:lower:]' <"$expected_stdout_file" >"$tmp_file"
+            mv "$tmp_file" "$expected_stdout_file"
+        fi
+
+        if echo "$options" | grep -q "w"; then
+            tr -d ' \t' <"$result_stdout_file" >"$tmp_file"
+            mv "$tmp_file" "$result_stdout_file"
+            tr -d ' \t' <"$expected_stdout_file" >"$tmp_file"
             mv "$tmp_file" "$expected_stdout_file"
         fi
 
@@ -119,12 +126,12 @@ for test_file in .mygive/$ass_name/tests/*; do
 
         cmp -s "$expected_stdout_file" "$result_stdout_file"
 
-        if [ $? -eq 0 ];then
+        if [ $? -eq 0 ] && diff -q $expected_stderr_file $result_stderr_file >/dev/null && [ "$result_exit_code" -eq "$exit_status" ]; then
             echo "* Test $file_name passed."
-            passed_tests=$((passed_tests+1))
+            passed_tests=$((passed_tests + 1))
         else
             echo "* Test $file_name failed."
-            failed_tests=$((failed_tests+1))
+            failed_tests=$((failed_tests + 1))
 
             # result_size=$(stat -f"%z" "$result_stdout_file")
             # expected_result_size=$(stat -f"%z" "$expected_stdout_file")
@@ -134,57 +141,122 @@ for test_file in .mygive/$ass_name/tests/*; do
             result_size=$(stat -c%s "$result_stdout_file")
             expected_result_size=$(stat -c%s "$expected_stdout_file")
 
-            if [ ! -s "$expected_stdout_file" ] && [ -s "$result_stdout_file" ];then
-                echo "--- No stdout expected, these $result_size bytes produced:"
-                cat "$result_stdout_file"
-                echo ""
-            elif [ ! -s "$result_stdout_file" ] && [ -s "$expected_stdout_file" ];then
-                echo "--- No stdout produced, these $expected_result_size bytes expected:"
-                cat "$expected_stdout_file"
-                echo ""
-            elif [ $(($result_size - $expected_result_size)) -eq 1 ] && [ "$result_char_result" = "" ];then
-                new_expected_file=$(mktemp)
-                cat "$expected_stdout_file" > "$new_expected_file"
-                printf "\n" >> "$new_expected_file"
-                if cmp -s "$new_expected_file" "$result_stdout_file";then
-                    echo "Extra newline at end of stdout"
+            if cmp -s "$expected_stdout_file" "$result_stdout_file"; then
+            :
+            else
+                if [ ! -s "$expected_stdout_file" ] && [ -s "$result_stdout_file" ]; then
+                    echo "--- No stdout expected, these $result_size bytes produced:"
+                    cat "$result_stdout_file"
+                    echo ""
+                elif [ ! -s "$result_stdout_file" ] && [ -s "$expected_stdout_file" ]; then
+                    echo "--- No stdout produced, these $expected_result_size bytes expected:"
+                    cat "$expected_stdout_file"
+                    echo ""
+                elif [ $((result_size - expected_result_size)) -eq 1 ] && [ "$result_char_result" = "" ]; then
+                    new_expected_file=$(mktemp)
+                    cat "$expected_stdout_file" >"$new_expected_file"
+                    printf "\n" >>"$new_expected_file"
+                    if cmp -s "$new_expected_file" "$result_stdout_file"; then
+                        echo "Extra newline at end of stdout"
+                    else
+                        echo "--- Incorrect stdout of $result_size bytes:"
+                        cat "$result_stdout_file"
+                        echo ""
+
+                        echo "--- Correct stdout is these $expected_result_size bytes:"
+                        cat "$expected_stdout_file"
+                        echo ""
+                    fi
+                elif [ $((expected_result_size - result_size)) -eq 1 ] && [ "$expected_char_result" = "" ]; then
+                    new_result_file=$(mktemp)
+                    cat "$result_stdout_file" >"$new_result_file"
+                    printf "\n" >>"$new_result_file"
+                    if cmp -s "$new_result_file" "$expected_stdout_file"; then
+                        echo "Missing newline at end of stdout"
+                    else
+                        echo "--- Incorrect stdout of $result_size bytes:"
+                        cat "$result_stdout_file"
+                        echo ""
+
+                        echo "--- Correct stdout is these $expected_result_size bytes:"
+                        cat "$expected_stdout_file"
+                        echo ""
+                    fi
                 else
                     echo "--- Incorrect stdout of $result_size bytes:"
                     cat "$result_stdout_file"
                     echo ""
-                    
+
                     echo "--- Correct stdout is these $expected_result_size bytes:"
                     cat "$expected_stdout_file"
                     echo ""
                 fi
-            elif [ $(($expected_result_size - $result_size)) -eq 1 ] && [ "$expected_char_result" = "" ];then
-                new_result_file=$(mktemp)
-                cat "$result_stdout_file" > "$new_result_file"
-                printf "\n" >> "$new_result_file"
-                if cmp -s "$new_result_file" "$expected_stdout_file";then
-                    echo "Missing newline at end of stdout"
-                else
-                    echo "--- Incorrect stdout of $result_size bytes:"
+            fi
+            # result_stderr_size=$(stat -f"%z" "$result_stderr_file")
+            # expected_stderr_size=$(stat -f"%z" "$expected_stderr_file")
+
+            result_errchar_result=$(tail -c 1 "$result_stderr_file")
+            expected_errchar_result=$(tail -c 1 "$expected_stderr_file")
+            result_stderr_size=$(stat -c%s "$result_stderr_file")
+            expected_stderr_size=$(stat -c%s "$expected_stderr_file")
+            if diff -q $expected_stderr_file $result_stderr_file >/dev/null; then
+                :
+            else
+                if [ ! -s "$expected_stderr_file" ] && [ -s "$result_stderr_file" ]; then
+                    echo "--- No stderr expected, these $result_stderr_size bytes produced:"
                     cat "$result_stdout_file"
                     echo ""
-                    
-                    echo "--- Correct stdout is these $expected_result_size bytes:"
-                    cat "$expected_stdout_file"
+                elif [ ! -s "$result_stderr_file" ] && [ -s "$expected_stderr_file" ]; then
+                    echo "--- No stderr produced, these $expected_stderr_size bytes expected:"
+                    cat "$expected_stderr_file"
+                    echo ""
+                elif [ $((result_stderr_size - expected_stderr_size)) -eq 1 ] && [ "$result_errchar_result" = "" ]; then
+                    new_expected_file=$(mktemp)
+                    cat "$expected_stderr_file" >"$new_expected_file"
+                    printf "\n" >>"$new_expected_file"
+                    if cmp -s "$new_expected_file" "$result_stderr_file"; then
+                        echo "Extra newline at end of stderr"
+                    else
+                        echo "--- Incorrect stderr of $result_stderr_size bytes:"
+                        cat "$result_stderr_file"
+                        echo ""
+
+                        echo "--- Correct stderr is these $expected_stderr_size bytes:"
+                        cat "$expected_stderr_file"
+                        echo ""
+                    fi
+                elif [ $((expected_stderr_size - result_stderr_size)) -eq 1 ] && [ "$expected_errchar_result" = "" ]; then
+                    new_result_file=$(mktemp)
+                    cat "$result_stderr_file" >"$new_result_file"
+                    printf "\n" >>"$new_result_file"
+                    if cmp -s "$new_result_file" "$expected_stderr_file"; then
+                        echo "Missing newline at end of stderr"
+                    else
+                        echo "--- Incorrect stderr of $result_stderr_size bytes:"
+                        cat "$result_stderr_file"
+                        echo ""
+
+                        echo "--- Correct stderr is these $expected_stderr_size bytes:"
+                        cat "$expected_stderr_file"
+                        echo ""
+                    fi
+                else
+                    echo "--- Incorrect stderr of $result_stderr_size bytes:"
+                    cat "$result_stderr_file"
+                    echo ""
+
+                    echo "--- Correct stderr is these $expected_result_size bytes:"
+                    cat "$expected_stderr_file"
                     echo ""
                 fi
-             else
-                echo "--- Incorrect stdout of $result_size bytes:"
-                cat "$result_stdout_file"
-                echo ""
-                            
-                echo "--- Correct stdout is these $expected_result_size bytes:"
-                cat "$expected_stdout_file"
-                echo ""
+            fi
+
+            if [ "$result_exit_code" -ne "$exit_status" ]; then
+                echo "Exit status of $result_exit_code incorrect should be $exit_status"
             fi
         fi
-   done < "$tmp_list"
-#    rm -rf "$test_dir"
+    done <"$tmp_list"
+    #    rm -rf "$test_dir"
 done
 
 echo "** $passed_tests tests passed, $failed_tests tests failed"
-
